In [39]:
import pandas as pd
import numpy as np
import json

# Dataset

## Dataset 1 - DDXPlus 

in french

In [40]:
# Evidence json

with open("./data/dataset1/release_evidences.json", "r") as json_file:
    evidence = json.load(json_file)

In [42]:
type(evidence)

dict

In [44]:
evidence["fievre"]

{'name': 'fievre',
 'code_question': 'fievre',
 'question_fr': 'Avez-vous objectivé ou ressenti de la fièvre?',
 'question_en': 'Do you have a fever (either felt or measured with a thermometer)?',
 'is_antecedent': False,
 'default_value': 0,
 'value_meaning': {},
 'possible-values': [],
 'data_type': 'B'}

In [45]:
# Pathology description

with open("./data/dataset1/release_conditions.json", "r") as json_file:
    conditions = json.load(json_file)

In [46]:
type(conditions)

dict

In [47]:
conditions.keys()

dict_keys(['Pneumothorax spontané', 'Céphalée en grappe', 'Syndrome de Boerhaave', 'Fracture de côte spontanée', 'RGO', 'VIH (Primo-infection)', 'Anémie', 'Pharyngite virale', 'Hernie inguinale', 'Myasthénie grave', 'Coqueluche', 'Anaphylaxie', 'Épiglottite', 'Syndrome de Guillain-Barré', 'Laryngite aigue', 'Laryngo-trachéo-bronchite (Croup)', 'TSVP', 'Fibrillation auriculaire/Flutter auriculaire', 'Bronchiectasies', 'Rhinite allergique', 'Chagas', 'Scombroïde', 'Myocardite', 'Laryngospasme', 'Réaction dystonique aïgue', 'Oedème localisé ou généralisé sans atteinte pulmonaire associée', 'Lupus érythémateux disséminé (LED)', 'Tuberculose', 'Angine instable', 'Angine stable', 'Ebola', 'Otite moyenne aigue (OMA)', 'Attaque de panique', 'Asthme exacerbé ou bronchospasme', 'Bronchite', 'Exacerbation aigue de MPOC et/ou surinfection associée', 'Embolie pulmonaire', 'IVRS ou virémie', 'Possible influenza ou syndrome virémique typique', 'Pneumonie', 'Rhinosinusite aigue', 'Rhinosinusite chronique', 'Bronchiolite', 'néoplasie pulmonaire', 'Possible NSTEMI / STEMI', 'Sarcoïdose', 'Néoplasie du pancréas', 'OAP/Surcharge pulmonaire', 'Péricardite'])

In [48]:
conditions["Bronchiolite"]

{'condition_name': 'Bronchiolite',
 'cond-name-fr': 'Bronchiolite',
 'cond-name-eng': 'Bronchiolitis',
 'icd10-id': 'j21',
 'symptoms': {'toux': {},
  'dyspn': {},
  'boire_ped': {},
  'rhino_clair': {},
  'fievre': {},
  'wheez': {},
  'apnee': {}},
 'antecedents': {'vaccination': {},
  'momasthma': {},
  'crowd': {},
  'suburb': {},
  'rural': {},
  'trav1': {}},
 'severity': 3}

In [49]:
# Train

df = pd.read_csv("./data/dataset1/release_train_patients.csv")

In [50]:
df.head()

,AGE,DIFFERENTIAL_DIAGNOSIS,SEX,PATHOLOGY,EVIDENCES,INITIAL_EVIDENCE
0,18,"[['Bronchite', 0.19171203430383882], ['Pneumon...",M,IVRS ou virémie,"['crowd', 'diaph', 'douleurxx', 'douleurxx_car...",fievre
1,21,"[['VIH (Primo-infection)', 0.5189500564407601]...",M,VIH (Primo-infection),"['adp_dlr', 'atcd_its', 'diaph', 'diarrhee', '...",diaph
2,19,"[['Bronchite', 0.11278064619119596], ['Pneumon...",F,Pneumonie,"['douleurxx', 'douleurxx_carac_@_un_coup_de_co...",expecto
3,34,"[['IVRS ou virémie', 0.23859396799565236], ['C...",F,IVRS ou virémie,"['crowd', 'douleurxx', 'douleurxx_carac_@_une_...",douleurxx
4,36,"[['IVRS ou virémie', 0.23677812769175735], ['P...",M,IVRS ou virémie,"['dayc', 'diaph', 'douleurxx', 'douleurxx_cara...",toux

In [51]:
df.columns

Index(['AGE', 'DIFFERENTIAL_DIAGNOSIS', 'SEX', 'PATHOLOGY', 'EVIDENCES',
       'INITIAL_EVIDENCE'],
      dtype='object')

## Dataset 2

In [87]:
df = pd.read_csv("./data/dataset2/Disease_symptom_and_patient_profile_dataset.csv")

In [88]:
df.shape

(349, 10)

In [89]:
df.columns

Index(['Disease', 'Fever', 'Cough', 'Fatigue', 'Difficulty Breathing', 'Age',
       'Gender', 'Blood Pressure', 'Cholesterol Level', 'Outcome Variable'],
      dtype='object')

In [90]:
df.head()

,Disease,Fever,Cough,Fatigue,Difficulty Breathing,Age,Gender,Blood Pressure,Cholesterol Level,Outcome Variable
0,Influenza,Yes,No,Yes,Yes,19,Female,Low,Normal,Positive
1,Common Cold,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
2,Eczema,No,Yes,Yes,No,25,Female,Normal,Normal,Negative
3,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive
4,Asthma,Yes,Yes,No,Yes,25,Male,Normal,Normal,Positive

In [91]:
df["Disease"].value_counts()

Disease
Asthma               23
Stroke               16
Osteoporosis         14
Diabetes             10
Hypertension         10
                     ..
Schizophrenia         1
Gout                  1
Testicular Cancer     1
Tonsillitis           1
Williams Syndrome     1
Name: count, Length: 116, dtype: int64

In [57]:
# may helps with the patient details

## Dataset 3

In [92]:
df1 = pd.read_csv("./data/dataset3/disease_diagnosis.csv")

In [93]:
df1.shape

(2000, 13)

In [94]:
df1.head()

,Patient_ID,Age,Gender,Symptom_1,Symptom_2,Symptom_3,Heart_Rate_bpm,Body_Temperature_C,Blood_Pressure_mmHg,Oxygen_Saturation_%,Diagnosis,Severity,Treatment_Plan
0,1,74,Male,Fatigue,Sore throat,Fever,69,39.4,132/91,94,Flu,Moderate,Medication and rest
1,2,66,Female,Sore throat,Fatigue,Cough,95,39.0,174/98,98,Healthy,Mild,Rest and fluids
2,3,32,Male,Body ache,Sore throat,Fatigue,77,36.8,136/60,96,Healthy,Mild,Rest and fluids
3,4,21,Female,Shortness of breath,Headache,Cough,72,38.9,147/82,99,Healthy,Mild,Rest and fluids
4,5,53,Male,Runny nose,Sore throat,Fatigue,100,36.6,109/106,92,Healthy,Mild,Rest and fluids

In [63]:
df1["Diagnosis"].value_counts()

Diagnosis
Healthy       1167
Bronchitis     334
Flu            292
Cold           163
Pneumonia       44
Name: count, dtype: int64

In [64]:
# May be helped with patient details

## Dataset 4

In [66]:
df = pd.read_csv("./data/dataset4/Diseases_Symptoms.csv")

In [67]:
df.shape

(400, 4)

In [68]:
df.columns

Index(['Code', 'Name', 'Symptoms', 'Treatments'], dtype='object')

In [69]:
df.head()

,Code,Name,Symptoms,Treatments
0,1,Panic disorder,"Palpitations, Sweating, Trembling, Shortness o...","Antidepressant medications, Cognitive Behavior..."
1,2,Vocal cord polyp,"Hoarseness, Vocal Changes, Vocal Fatigue","Voice Rest, Speech Therapy, Surgical Removal"
2,3,Turner syndrome,"Short stature, Gonadal dysgenesis, Webbed neck...","Growth hormone therapy, Estrogen replacement t..."
3,4,Cryptorchidism,"Absence or undescended testicle(s), empty scro...",Observation and monitoring (in cases of mild o...
4,5,Ethylene glycol poisoning-1,"Nausea, vomiting, abdominal pain, General mala...","Supportive Measures, Gastric Decontamination, ..."

In [71]:
# Disease - symptoms - treatments

In [72]:
df1 = pd.read_csv("./data/dataset4/symbipredict_2022.csv")

In [73]:
df1.shape

(4961, 133)

In [74]:
df1.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [77]:
sample = df1.iloc[0]

In [79]:
sample.index

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [ ]:
for feat in sample.index:
    print(feat, sample[feat])

In [81]:
df1["prognosis"].value_counts()

prognosis
Fungal Infection                 121
Allergy                          121
GERD                             121
Chronic Cholestasis              121
Drug Reaction                    121
Peptic Ulcer Disease             121
AIDS                             121
Diabetes                         121
Gastroenteritis                  121
Bronchial Asthma                 121
Hypertension                     121
Migraine                         121
Cervical Spondylosis             121
Paralysis (brain hemorrhage)     121
Jaundice                         121
Malaria                          121
Chickenpox                       121
Dengue                           121
Typhoid                          121
Hepatitis A                      121
Hepatitis B                      121
Hepatitis C                      121
Hepatitis D                      121
Hepatitis E                      121
Alcoholic Hepatitis              121
Tuberculosis                     121
Common Cold                      121
Pneumonia                        121
Dimorphic Hemmorhoids (piles)    121
Heart Attack                     121
Varicose Veins                   121
Hypothyroidism                   121
Hyperthyroidism                  121
Hypoglycemia                     121
Osteoarthritis                   121
Arthritis                        121
Vertigo                          121
Acne                             121
Urinary Tract Infection          121
Psoriasis                        121
Impetigo                         121
Name: count, dtype: int64

## Dataset 5

In [82]:
df = pd.read_csv("./data/dataset5/SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv")

In [83]:
df.shape

(130637, 6)

In [84]:
df.columns

Index(['Symptoms', 'Gender', 'Age', 'Duration', 'Severity',
       'Final Recommendation'],
      dtype='object')

In [85]:
df.head()

,Symptoms,Gender,Age,Duration,Severity,Final Recommendation
0,"Unwanted weight loss, Mouth sore, Persistent m...",Male,6-15 years,Greater than 3 days,Severe,Doctor Consultation
1,"Feeling tired, Shortness breath, Blue skin col...",Female,below 5 years,Greater than 3 days,Severe,Doctor Consultation
2,"False beliefs, Seeing, hearing things are not ...",Male,6-15 years,Greater than 3 days,Mild,Doctor Consultation
3,"Chest pain, Shortness breath, Fast heart rate,...",Female,above 45 years,Greater than 3 days,Moderate,Doctor Consultation
4,"fever, vaginal bleeding, painful urination, di...",Female,below 5 years,Less than 3 days,Severe,Doctor Consultation

In [86]:
df["Final Recommendation"].value_counts()

Final Recommendation
Doctor Consultation    126171
OTC Drug                 4466
Name: count, dtype: int64

## Dataset 2

In [9]:
df2 = pd.read_csv("./data/DiseaseAndSymptoms.csv")

In [10]:
df2.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df2.shape

(4920, 18)

In [12]:
df2["Disease"].value_counts()

Disease
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [35]:
# Disease and symptoms

from collections import defaultdict

diseases = defaultdict(list)
features = df2.columns

for idx, row in df2.iterrows():

    disease = row["Disease"]

    symptoms = []

    for feature in features:

        if feature.startswith("Symptom") and str(row[feature]) != "nan":
            symptoms.append(row[feature].strip())
        
    diseases[disease].extend(symptoms)

diseases = {key: list(set(value)) for key, value in diseases.items()}

In [37]:
diseases["Heart attack"]

['breathlessness', 'vomiting', 'chest_pain', 'sweating']